# Generated by Django 5.1.5 on 2025-03-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friendlist_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='profile_img',
        ),
    ]
